### ISSUE TITLE
message serialization: should tangle arrays be alphabetized too?

### ISSUE THREAD

**Issue by ahdinosaur** [staltz/ppppp-db#2]
as a continuation of #1, i wonder if we should alphabetize the tangle arrays, since they are strings.

the use case is if someone wanted to store messages in an SQL database. with this change, as far as i can tell we'd be able to store the message metadata in different tables, columns, rows, whatever. (note: the content would be need to be stored as is, in a JSON column.) then you could re-construct the original message, in the exact same format. otherwise at the moment, we'd need to keep track of the original order of tangle arrays, if we want to re-construct the original message.

**Comment by staltz** [comment]
Oh, great use case you wrote there to justify the sort. I fully agree and am happy to accept the change to sort tangle arrays.
