### ISSUE TITLE
more message serialization: Canonical JSON?

### ISSUE THREAD

**Issue by ahdinosaur** [staltz/ppppp-db#3]
follow on from #1 and #2,

i'm not sure [`fast-json-stable-stringify`](https://github.com/epoberezkin/fast-json-stable-stringify/) is the best way to produce determinstic JSON.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort :

> The default sort order is ascending, built upon converting the elements into strings, then comparing their sequences of UTF-16 code units values.

the reason is because JavaScript strings are actually UTF-16 strings... :open_mouth: 

i mention this because the default `Array#sort` is what [`fast-json-stable-stringify`](https://github.com/epoberezkin/fast-json-stable-stringify/) uses.

ideally we'd be sorting the UTF-8 directly? like [`compare-utf8`](https://github.com/rocicorp/compare-utf8/blob/main/src/index.js). so any alternate language implementations don't also need to convert to UTF-16 in order to be equally deterministic.

**Comment by ahdinosaur** [comment]
found a [Canonical JSON](https://wiki.laptop.org/go/Canonical_JSON) with interesting ideas:

- "It is suggested that unicode strings be represented as the UTF-8 encoding of unicode [Normalization Form C](http://www.unicode.org/reports/tr15/)"
- "Floating point numbers are not allowed in canonical JSON. Neither are leading zeros or "minus 0" for integers."

i learned that JavaScript has a [`String#normalize`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize) function. the normalization they recommend is "NFC".

**Comment by ahdinosaur** [comment]
[JSON Canonical Form](https://gibson042.github.io/canonicaljson-spec/)

**Comment by ahdinosaur** [comment]
[JSON Canonicalization Scheme (JCS)](https://datatracker.ietf.org/doc/html/rfc8785)

**Comment by staltz** [comment]
> [JSON Canonicalization Scheme (JCS)](https://datatracker.ietf.org/doc/html/rfc8785)

I totally agree with using something like this. I thought `fast-json-stable-stringify` was good enough, and I even looked at its source code, but this UTF-16 thing slipped through! JCS seems great, and I'm happy to defer to people who have thought about this exact problem in details. Let's use their outcomes.

**Comment by staltz** [comment]
Seems like https://www.npmjs.com/package/canonicalize follows JCS?

**Comment by staltz** [comment]
> Seems like https://www.npmjs.com/package/canonicalize follows JCS?

Nevermind, you used this in your PR :see_no_evil:

**Comment by ahdinosaur** [comment]
> this UTF-16 thing slipped through

to be fair, JSC does the UTF-16 thing, but okay with me because as you say, i'd much rather defer to people who have thought about this exact problem in details, we need every possible wiggly bit uncovered and documented.

all the modules that are "stable" or "deterministic" make sense if you're only using hashes using the same code in the same language, but we need something "canonical" that is _well-specified_ enough to write in another language.

i did already notice `canonicalize` wasn't strictly following the spec, so i have a pull request there too: https://github.com/erdtman/canonicalize/pull/12
